import lmSupportLogo from './assets/logos/lm-support-symbol.svg'
import { useState } from 'react'
import { ArrowRight, BookOpen, ChevronRight, Clock3, Headphones, Home, LifeBuoy, LockKeyhole, LogOut, Mail, Menu, MessageCircle, MonitorSmartphone, Plus, Search, TicketCheck, UserRound, X } from 'lucide-react'

function BrandMark(){return <div className="brand-mark"><img src={lmSupportLogo} alt="LM Improve IT" /></div>}
const tickets=[{id:'#1042',title:'Problem med e-post',status:'Pågår',date:'Idag 09:42',tone:'progress'},{id:'#1038',title:'Behöver hjälp med inloggning',status:'Öppen',date:'26 sep',tone:'open'},{id:'#1029',title:'Installation av programvara',status:'Avslutad',date:'22 sep',tone:'closed'}]

function Login({onLogin}:{onLogin:()=>void}){return <main className="login-page"><section className="brand-panel"><div className="brand-copy"><BrandMark/><p className="eyebrow">LM Improve IT</p><h1>Support när du behöver den.</h1><p className="intro">Skapa ärenden, följ status och prata direkt med supporten – samlat på ett ställe.</p></div><div className="brand-footer"><MessageCircle size={20}/><span>SupportApp 2.0</span></div></section><section className="login-panel"><div className="login-card"><div className="mobile-brand"><BrandMark/><span>Support</span></div><p className="eyebrow">Välkommen tillbaka</p><h2>Logga in</h2><p className="helper">Använd ditt konto för att komma till dina supportärenden.</p><form onSubmit={e=>{e.preventDefault();onLogin()}}><label htmlFor="email">E-postadress</label><div className="input-wrap"><Mail size={19}/><input id="email" type="email" placeholder="namn@foretag.se"/></div><div className="label-row"><label htmlFor="password">Lösenord</label><button className="text-button" type="button">Glömt lösenord?</button></div><div className="input-wrap"><LockKeyhole size={19}/><input id="password" type="password" placeholder="••••••••"/></div><button className="primary-button" type="submit">Logga in <ArrowRight size={19}/></button></form><p className="login-note">Behöver du hjälp med ditt konto? <button className="text-button" type="button">Kontakta support</button></p></div></section></main>}

function Dashboard({onLogout}:{onLogout:()=>void}){const[open,setOpen]=useState(false);return <div className="app-shell"><aside className={'sidebar '+(open?'sidebar-open':'')}><div className="sidebar-brand"><BrandMark/><div><strong>Support</strong><small>LM Improve IT</small></div><button className="close-menu" onClick={()=>setOpen(false)} aria-label="Stäng meny"><X size={21}/></button></div><nav><a className="nav-link active" href="#"><Home/>Översikt</a><a className="nav-link" href="#"><LifeBuoy/>Mina ärenden</a><a className="nav-link" href="#"><BookOpen/>Guider</a></nav><div className="sidebar-bottom"><div className="profile-mini"><div className="avatar">A</div><div><strong>Amanda</strong><small>Mitt konto</small></div></div><button className="logout" onClick={onLogout}><LogOut/>Logga ut</button></div></aside>{open&&<button className="menu-backdrop" onClick={()=>setOpen(false)} aria-label="Stäng meny"/>}<main className="dashboard"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Öppna meny"><Menu/></button><div className="search-box"><Search/><input placeholder="Sök bland dina ärenden..."/></div><button className="user-button"><UserRound/><span>Amanda</span></button></header><div className="dashboard-content"><section className="welcome-row"><div><p className="eyebrow">Översikt</p><h1>Hej Amanda! 👋</h1><p>Vad kan vi hjälpa dig med idag?</p></div><button className="create-ticket"><Plus/>Skapa supportärende</button></section><section className="quick-grid"><Quick icon={<LifeBuoy/>} title="Nytt supportärende" text="Beskriv problemet så hjälper vi dig." primary/><Quick icon={<MonitorSmartphone/>} title="Fjärrsupport" text="Få hjälp direkt på din dator."/><Quick icon={<BookOpen/>} title="Guider" text="Hitta svar och enkla instruktioner."/></section><section className="stats-grid"><Stat icon={<LifeBuoy/>} number="2" text="Öppna ärenden" tone="open"/><Stat icon={<Clock3/>} number="1" text="Pågående" tone="progress"/><Stat icon={<TicketCheck/>} number="8" text="Avslutade" tone="closed"/></section><section className="content-grid"><div className="panel tickets-panel"><div className="panel-heading"><div><h2>Senaste ärenden</h2><p>Följ dina senaste supportärenden.</p></div><button>Visa alla <ArrowRight/></button></div><div className="ticket-list">{tickets.map(t=><button className="ticket-row" key={t.id}><div className="ticket-main"><span className="ticket-id">{t.id}</span><strong>{t.title}</strong><small>{t.date}</small></div><span className={'status '+t.tone}>{t.status}</span><ChevronRight/></button>)}</div></div><aside className="panel help-panel"><div className="help-icon"><Headphones/></div><h2>Behöver du snabb hjälp?</h2><p>Kontakta supporten direkt eller boka en tid som passar dig.</p><button className="outline-button"><Mail/>Kontakta support</button></aside></section></div></main></div>}
function Quick({icon,title,text,primary=false}:{icon:React.ReactNode,title:string,text:string,primary?:boolean}){return <button className={'quick-card '+(primary?'primary':'')}><div className="quick-icon">{icon}</div><div><strong>{title}</strong><span>{text}</span></div><ChevronRight/></button>}
function Stat({icon,number,text,tone}:{icon:React.ReactNode,number:string,text:string,tone:string}){return <div className="stat-card"><span className={'stat-icon '+tone}>{icon}</span><div><strong>{number}</strong><span>{text}</span></div></div>}
export default function App(){const[loggedIn,setLoggedIn]=useState(false);return loggedIn?<Dashboard onLogout={()=>setLoggedIn(false)}/>:<Login onLogin={()=>setLoggedIn(true)}/>}
